name: cool_car_admin
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.6
  connectivity_plus: ^6.1.3
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.0
  firebase_app_check: ^0.3.2+4
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_data_connect: ^0.1.0
  firebase_storage: ^12.4.5
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  flutter_riverpod: ^2.6.1
  geocoding: ^3.0.0
  google_sign_in: ^6.2.2
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/cool_car_admin_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/cool_car_admin_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/cool_car_logo.jpg
    - assets/facebook_icon.png
    - assets/google_icon.png
    - assets/default_profile.jpg
    - assets/building.jpg
    - assets/car.png
    - assets/placeholder.png
