// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhTspeDUN_BH6_teRoFg8lKS9-Ww7sUJA',
    appId: '1:975970303551:web:393ce1c1533e26d4f1428a',
    messagingSenderId: '975970303551',
    projectId: 'cool-car-user-1',
    authDomain: 'cool-car-user-1.firebaseapp.com',
    storageBucket: 'cool-car-user-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDuC0ewgaTpmnkLUTZWHfMNpcKSgl0Gjw',
    appId: '1:975970303551:android:3f724ea8f8eaae5bf1428a',
    messagingSenderId: '975970303551',
    projectId: 'cool-car-user-1',
    storageBucket: 'cool-car-user-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy-YJswNee-M4N4r_ImkhvbrH6LoOULNw',
    appId: '1:975970303551:ios:8cbf7589694b9674f1428a',
    messagingSenderId: '975970303551',
    projectId: 'cool-car-user-1',
    storageBucket: 'cool-car-user-1.firebasestorage.app',
    androidClientId: '975970303551-2q4vlech7n9s3jvd4kbpusdhnequu1hm.apps.googleusercontent.com',
    iosClientId: '975970303551-3udlat6s41ojg41rdqjfqdq1el2940ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolCarAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy-YJswNee-M4N4r_ImkhvbrH6LoOULNw',
    appId: '1:975970303551:ios:8cbf7589694b9674f1428a',
    messagingSenderId: '975970303551',
    projectId: 'cool-car-user-1',
    storageBucket: 'cool-car-user-1.firebasestorage.app',
    androidClientId: '975970303551-2q4vlech7n9s3jvd4kbpusdhnequu1hm.apps.googleusercontent.com',
    iosClientId: '975970303551-3udlat6s41ojg41rdqjfqdq1el2940ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolCarAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhTspeDUN_BH6_teRoFg8lKS9-Ww7sUJA',
    appId: '1:975970303551:web:74bcf0913444199ff1428a',
    messagingSenderId: '975970303551',
    projectId: 'cool-car-user-1',
    authDomain: 'cool-car-user-1.firebaseapp.com',
    storageBucket: 'cool-car-user-1.firebasestorage.app',
  );
}
